; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter

build_flags =
    # 1 = Hardware CDC mode (tells the chip to talk over the physical USB-C lines)
    -DARDUINO_USB_MODE=1
    # 1 = Redirects all standard 'Serial' commands to the USB-C port upon booting up
    -DARDUINO_USB_CDC_ON_BOOT=1