# -----------------------------
# Plain MQTT - development
# -----------------------------
listener 1883

allow_anonymous false
password_file ./passwd


# -----------------------------
# MQTT over TLS
# -----------------------------
listener 8883

allow_anonymous false
password_file ./passwd

cafile ./certs/ca.crt
certfile ./certs/broker.crt
keyfile ./certs/broker.key